spring:
  application:
    name: SafetyAndCheap
  datasource:
    url: jdbc:postgresql://localhost:5432/safety_and_cheap
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: optional:secrets.properties[.properties]
jwt:
  access-token-key: ${JWT_ACCESS_TOKEN_KEY}
  refresh-token-key: ${JWT_REFRESH_TOKEN_KEY}
  ttl-hours: 36
sms:
  login: ${SMS_LOGIN}
  password: ${SMS_PASSWORD}
